modLoader="javafml"
loaderVersion="[36,)"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
issueTrackerURL="https://github.com/CoffeeCatRailway/SoulPowered/issues"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${name}"
logoFile="logo.png"
credits="SilentChaos512"
authors="${author}"
description='''
A simple tech mod with a hint of magic!
'''

[[dependencies.soulpowered]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"
[[dependencies.soulpowered]]
modId="minecraft"
mandatory=true
versionRange="[1.16.4,1.16.5]"
ordering="NONE"
side="BOTH"
[[dependencies.soulpowered]]
modId="jei"
mandatory=false
versionRange="[7,]"
ordering="NONE"
side="CLIENT"
[[dependencies.soulpowered]]
modId="curios"
mandatory=true
versionRange="[1.16.5,]"
ordering="NONE"
side="BOTH"