modLoader="javafml"
loaderVersion="[35,)"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
issueTrackerURL="https://github.com/CoffeeCatRailway/GITHUB REPO/issues"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${name}"
# logoFile="logo.png"
# credits=""
authors="${author}"
description='''

'''

[[dependencies.soulpowered]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="BOTH"
[[dependencies.soulpowered]]
modId="minecraft"
mandatory=true
versionRange="[1.16.4]"
ordering="NONE"
side="BOTH"
# [[dependencies.soulpowered]]
# modId="jei"
# mandatory=false
# versionRange="[7,]"
# ordering="NONE"
# side="CLIENT"