@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package coffeecatrailway.soulpowered.common.item;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;