@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package coffeecatrailway.soulpowered.network.handler;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;