@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package coffeecatrailway.soulpowered.intergration.tinkers;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;