@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package coffeecatrailway.soulpowered.client.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;