@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package coffeecatrailway.soulpowered.common.inventory;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;